name: OSV-Scanner

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]
  schedule:
    - cron: '30 0 * * *'
  workflow_dispatch:

jobs:
  scan-repository:
    # Explicitly attach tokens directly to the job runner
    permissions:
      security-events: write
      contents: read
      
    uses: google/osv-scanner-action/.github/workflows/osv-scanner-reusable.yml@v2
 